name: "Dev package tests in GAP master"

on:
  #push:
  #pull_request:
  workflow_dispatch:
  schedule:
    # Every day at 4:15 AM UTC
    - cron: '15 4 * * *'

jobs:
  dev:
    name: "GAP master"
    uses: ./.github/workflows/dev-pkg-tests.yml
