name: "Run selected dev package tests"

on:
  #push:
  #pull_request:
  workflow_dispatch:
    inputs:
      # TODO Support providing a repo URL directly
      packages:
        description: 'Packages to test (whitespace separated e.g. "digraphs semigroups"; leave blank to test all)'
        required: false
        type: string
  workflow_call:

jobs:
  extract:
    name: "Assemble repository URLs to test"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: "Set up Python"
        uses: actions/setup-python@v2
      - name: "Install Python modules"
        run: pip3 install BeautifulSoup4
      - name: "Get current dev repos"
        id: matrix
        run: |
          JSON=`python3 get-repos.py ${{ github.event.inputs.packages }}`
          if [ "$JSON" = "{\"include\": []}" ]; then
            echo "No matching repositories found"
            exit 42
          fi
          echo "::set-output name=matrix::${JSON}"

  package:
    name: "${{ matrix.package }}"
    needs: extract
    #if: ${{ needs.extract.outputs.matrix != '{"include": []}' }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.extract.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2

      - run: docker pull ghcr.io/gap-system/gap-docker-master:master

      - name: "Clone and compile package"
        timeout-minutes: 20
        run: >
          docker run
          -v $PWD:/home/workspace
          ghcr.io/gap-system/gap-docker-master:master
          /bin/sh -c "PKG_NAME=${{ matrix.package }} REPO_URL=${{ matrix.repo_url }} /home/workspace/dev-pkg.sh"

      # TODO: Skip trying to test packages without tests

      - name: "Run package tests with default packages loaded"
        timeout-minutes: 20
        run: >
          docker run
          -v $PWD:/home/workspace
          ghcr.io/gap-system/gap-docker-master:master
          /bin/sh -c "PKG_NAME=${{ matrix.package }} /home/workspace/pkg-tests.sh"

      - name: "Run package tests with minimal packages loaded"
        timeout-minutes: 20
        run: >
          docker run
          -v $PWD:/home/workspace
          ghcr.io/gap-system/gap-docker-master:master
          /bin/sh -c "PKG_NAME=${{ matrix.package }} /home/workspace/pkg-tests.sh -A"
