name: "Dev package tests in GAP master"

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 4:15 AM UTC
    - cron: '15 4 * * 1'

jobs:
  dev:
    name: "GAP master"
    uses: ./.github/workflows/dev-pkg-tests.yml
