name: "GAP master test suites"

on:
  #push:
  #pull_request:
  workflow_dispatch:
  schedule:
    # Every day at 2:15 AM UTC
    - cron: '15 2 * * *'

jobs:
  install-bugfix-standard:
    name: "GAP"
    uses: ./.github/workflows/gap-tests.yml
    with:
      container: >-
        ["master"]
      suite: >-
        ["testinstall", "testbugfix", "teststandard"]
      pkgs: >-
        ["no", "auto", "all"]

  loadpackages:
    name: "GAP"
    uses: ./.github/workflows/gap-tests.yml
    with:
      container: >-
        ["master"]
      suite: >-
        ["testloadpackages"]
      pkgs: >-
        ["single", "singleonlyneeded", "all", "allreversed"]
