name: "GAP stable-4.11 test suites"

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 1:15 AM UTC
    - cron: '15 1 * * 1'

jobs:
  install-bugfix-standard:
    name: "GAP"
    uses: ./.github/workflows/gap-tests.yml
    with:
      container: >-
        ["stable-4.11"]
      suite: >-
        ["testinstall", "testbugfix", "teststandard"]
      pkgs: >-
        ["no", "auto", "all"]

  loadpackages:
    name: "GAP"
    uses: ./.github/workflows/gap-tests.yml
    with:
      container: >-
        ["stable-4.11"]
      suite: >-
        ["testloadpackages"]
      pkgs: >-
        ["single", "singleonlyneeded", "all", "allreversed"]
