name: "GAP test suites"

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  testsuites:
    name: "GAP ${{ matrix.container }} / ${{ matrix.test-suite }} / ${{ matrix.pkgs }} packages"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        container:
          - master
          - stable-4.11
        test-suite:
          - testinstall
          - testbugfix
          - teststandard
        pkgs:
          - no
          - auto
          - all

    steps:
      - uses: actions/checkout@v2

      - name: "Constructing the full Docker container URL"
        id: container
        run: echo "::set-output name=url::ghcr.io/gap-system/gap-docker-${{ matrix.container }}:master"

      - name: "Pull the container ${{ steps.container.outputs.url }}"
        run: docker pull ${{ steps.container.outputs.url }}

      - name: "Run GAP's ${{ matrix.test-suite }} test suite in the container with ${{ matrix.pkgs }} packages"
        run: |
          docker run -v $PWD:/home/workspace ${{ steps.container.outputs.url }} /bin/sh -c "TEST_SUITE=${{ matrix.test-suite }} GAPPKG=${{ matrix.pkgs }} CONTAINER=${{ matrix.container }} /home/workspace/gap-ci.sh"
          # retired variables: LANG=en_GB.UTF-8

  loadpackages:
    name: "GAP ${{ matrix.container }} / testloadpackages / ${{ matrix.pkgs }}"
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        container:
          - master
          - stable-4.11
        pkgs:
          - single
          - singleonlyneeded
          - all
          - allreversed

    steps:
      - uses: actions/checkout@v2

      - name: "Constructing the full Docker container URL"
        id: container
        run: echo "::set-output name=url::ghcr.io/gap-system/gap-docker-${{ matrix.container }}:master"

      - name: "Pull the container ${{ steps.container.outputs.url }}"
        run: docker pull ${{ steps.container.outputs.url }}

      - name: "Run GAP's ${{ matrix.test-suite }} test suite in the container with ${{ matrix.pkgs }} packages"
        run: |
          docker run -v $PWD:/home/workspace ${{ steps.container.outputs.url }} /bin/sh -c "TEST_SUITE=testloadpackages GAPPKG=${{ matrix.pkgs }} CONTAINER=${{ matrix.container }} /home/workspace/gap-ci.sh"
