name: "Package tests in GAP master"

on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  pkg:
    name: "GAP master"
    uses: ./.github/workflows/pkg-tests.yml
    with:
      container: gap-docker-master
