name: "Package tests in GAP master"

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 3:30 AM UTC
    - cron: '30 3 * * 1'

jobs:
  pkg:
    name: "GAP master"
    uses: ./.github/workflows/pkg-tests.yml
    with:
      container: gap-docker-master
