name: "Package tests in GAP stable-4.11"

on:
  #push:
  #pull_request:
  workflow_dispatch:

jobs:
  pkg:
    name: "GAP stable-4.11"
    uses: ./.github/workflows/pkg-tests.yml
    with:
      container: gap-docker-stable-4.11
