name: "Package tests in GAP stable-4.11"

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 2:30 AM UTC
    - cron: '30 2 * * 1'

jobs:
  pkg:
    name: "GAP stable-4.11"
    uses: ./.github/workflows/pkg-tests.yml
    with:
      container: gap-docker-stable-4.11
