name: "Package tests in GAP master"

on:
  #push:
  #pull_request:
  workflow_dispatch:
  schedule:
    # Every day at 3:30 AM UTC
    - cron: '30 3 * * *'

jobs:
  pkg:
    name: "GAP master"
    uses: ./.github/workflows/pkg-tests.yml
    with:
      container: gap-docker-master
